# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.8'

services:
  yoli-api:
    image: yoli
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7029:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw