version: "3.8"

volumes:
 dbdata:

services:
  yoli-api:
    user: root
    image: yoli
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7029:80
    depends_on:
      - sqldb
    networks:
      - db_net

  sqldb:
    user: root
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: ${DBPassword}
      ACCEPT_EULA: "Y"
    ports:
      - 1436:1433
    volumes:
      - dbdata:/var/opt/mssql
    command: /opt/mssql/bin/sqlservr
    stdin_open: true
    networks:
      - db_net

  sqlcmd:
    user: root
    image: mcr.microsoft.com/mssql-tools:latest
    environment:
      SA_PASSWORD: ${DBPassword}
      DB_SERVER_NAME: "sqldb"
    volumes:
      - ./scripts:/opt/mssql_scripts
    command: /opt/mssql_scripts/init.sh
    stdin_open: true
    networks:
      - db_net

networks:
  db_net:
    name: db_net